Feat typescript shape loader
WTTJ/welcome-ui pull request #859
Opened 2021-07-08 13:16 UTC by DuarteParadela

2021-07-10 09:57 UTC, mleralec commented
cc @DuarteParadela, il faudrait rebase ta branche sur ` feat-typescript-2021`

2021-07-12 08:34 UTC, mleralec commented on packages/Loader/index.tsx
> +export type sizeType = 'xs' | 'sm' | 'md' | 'lg' | number | string
`export type Size = 'xs' | 'sm' | 'md' | 'lg'`

2021-07-12 08:34 UTC, mleralec commented on packages/Loader/index.tsx
> +  size?: 'xs' | 'sm' | 'md' | 'lg' | number | string
`size?: Size`

2021-07-12 08:35 UTC, mleralec commented on packages/Loader/index.tsx
> +export const Loader = forwardRef<HTMLDivElement, SystemProps & LoaderProps>(
on utilise plus SystemProps mais WuiProps à la place 😄

2021-07-12 08:36 UTC, mleralec commented on packages/Loader/styles.tsx
> +  SystemProps & ShapeProps & LoadingDotProps
Pas besoin de SystemProps ici

2021-07-12 08:36 UTC, mleralec commented on packages/Shape/index.tsx
> +export const Shape = forwardRef<HTMLDivElement, ShapeProps & SystemProps>(
remplacer SystemProps par WuiProps

2021-07-12 08:36 UTC, mleralec commented on packages/Shape/index.tsx
> +export type ShapeType = 'square' | 'circle'
`export type Shape = 'square' | 'circle'`

2021-07-12 08:37 UTC, mleralec commented on packages/Shape/styles.tsx
> +export const Shape = styled.div<ShapeProps & SystemProps>(
pas besoin de SystemProps ici non plus, tu peux raccourcir quand tu n'as qu'une propriété : 
```
export const Shape = styled.div<{ shape: Shape }>(
```

2021-07-12 08:37 UTC, mleralec commented on packages/Loader/styles.tsx
> +interface LoadingDotProps {
il manque un export de l'interface

2021-07-12 13:31 UTC, P1X3L approved these changes

2021-07-12 13:31 UTC, mleralec requested changes

2021-07-12 13:31 UTC, mleralec commented on packages/Shape/styles.ts
> +export const Shape = styled.div<{ shape: ShapeType } & WuiProps>(
pas besoin de WuiProps ici

2021-07-12 15:36 UTC, guillaumewttj commented on packages/Shape/styles.ts
> +export const Shape = styled.div<{ shape: ShapeType } & WuiProps>(
Hum, y'a bien un ${system} en bas 🤔 tu ne voudrais pas typer les style props alors qu'on peut en envoyer ?

2021-07-12 15:44 UTC, mleralec commented on packages/Shape/styles.ts
> +export const Shape = styled.div<{ shape: ShapeType } & WuiProps>(
Ah oui, mais du coup un `styled(Box)` -> éviterait d'avoir à rajouter ${system} et WuiProps non ? 🤔

2021-07-12 15:45 UTC, mleralec commented
Il manque la conversion des fichiers `test.js` aussi :muscle:

2021-07-19 14:55 UTC, mleralec approved these changes

2021-07-19 14:59 UTC, merged