feat: typescript on Radio component
WTTJ/welcome-ui pull request #888
Opened 2021-08-16 08:28 UTC by theo-mesnil

2021-08-16 08:41 UTC, cnairiwttj approved these changes

2021-08-16 12:10 UTC, anucreative commented on packages/Radio/index.tsx
> +      onChange && onChange(event)
```suggestion
      onClick?.(event)
      onChange?.(event)
```

2021-08-16 12:12 UTC, anucreative approved these changes

2021-08-16 13:56 UTC, theo-mesnil commented on packages/Radio/index.tsx
> +      onChange && onChange(event)
Hélas nous sommes dans une vielle version du wttj config... il faudra le mettre à jour plus tard.

2021-08-31 16:39 UTC, mleralec requested changes

2021-08-31 16:39 UTC, mleralec commented on packages/Radio/index.tsx
> +  onChange?: (event: React.MouseEvent<HTMLLabelElement>) => void
c'est plus un React.ChangeEvent sur le onChange non ?

2021-08-31 16:39 UTC, mleralec commented on packages/Radio/index.tsx
> +export const Radio = forwardRef<HTMLDivElement, RadioProps>(
La ref semble être passée à un composant de type Input -> `forwardRef<HTMLInputElement,`

2021-09-01 13:48 UTC, theo-mesnil commented on packages/Radio/index.tsx
> +export const Radio = forwardRef<HTMLDivElement, RadioProps>(
bien vu :)

2021-09-02 12:58 UTC, mleralec approved these changes

2021-09-02 13:03 UTC, merged