fix: replace rollup typescript plugin
WTTJ/welcome-ui pull request #915
Opened 2021-09-09 17:45 UTC by mleralec

2021-09-09 20:06 UTC, anucreative requested changes
Petit problème de `use(Layout)Effect` ?

2021-09-09 20:06 UTC, anucreative commented on packages/Utils/use-isomorphic-layout-effect.ts
> +export const useIsomorphicLayoutEffect = typeof window !== 'undefined' ? useEffect : useLayoutEffect
C'est l'inverse je crois. Si window est `undefined` on est sur le server donc il faut utiliser `useEffect` et utiliser `useLayoutEfffect` dans le browser. Sans negation est plus lisible aussi…

```
export const useIsomorphicLayoutEffect = typeof window === 'undefined' ? useEffect : useLayoutEffect
```

2021-09-09 20:06 UTC, anucreative commented on tsconfig.build.json
> +    // "noLib": true
Enleve les ?

2021-09-10 10:06 UTC, theo-mesnil approved these changes

2021-09-14 07:25 UTC, mleralec commented
expired, check https://github.com/WTTJ/welcome-ui/pull/919

2021-09-14 07:25 UTC, closed without merging